-------------------------------------------------------------------------------
-- Title      : tb_uart
-- Project    : Asylum
-------------------------------------------------------------------------------
-- File       : tb_uart.vhd
-- Author     : Mathieu Rosiere
-------------------------------------------------------------------------------
-- Description: Testbench for SBI UART with clock drift simulation
--              and parity tests (TX, RX and loopback, even and odd)
-------------------------------------------------------------------------------
-- Revisions  :
-- Date        Version  Author   Description
-- 2026-10-05  1.1      mrosiere Add parity tests (RX BFM, TX monitor,
--                               internal loopback) and parity error check
-------------------------------------------------------------------------------

library ieee;
use     ieee.std_logic_1164.all;
use     ieee.numeric_std.all;

library uvvm_util;
context uvvm_util.uvvm_util_context;

library bitvis_vip_sbi;
use     bitvis_vip_sbi.sbi_bfm_pkg.all;

library asylum;
use     asylum.sbi_pkg.all;
use     asylum.uart_pkg.all;
use     asylum.UART_csr_pkg.all;

entity tb_uart is
end tb_uart;

architecture sim of tb_uart is

  -- Configuration
  constant C_SCOPE         : string  := "TB_UART";
  constant CLOCK_FREQ      : integer := 50_000_000;
  constant BAUD_RATE       : integer := 115_200;
  constant CLK_PERIOD      : time    := 1 sec / CLOCK_FREQ;
  -- Bit period generated by the DUT : (CLOCK_FREQ/BAUD_RATE) clock cycles
  constant BIT_PERIOD      : time    := (CLOCK_FREQ / BAUD_RATE) * CLK_PERIOD;

  -- Parity mode of the TB BFM
  type     parity_t is (PARITY_NONE, PARITY_EVEN, PARITY_ODD);

  -- CSR values
  -- ctrl_tx / ctrl_rx : [0] enable, [1] parity enable, [2] parity odd, [3] loopback
  constant CTRL_EN         : std_logic_vector(7 downto 0) := x"01";
  constant CTRL_EN_EVEN    : std_logic_vector(7 downto 0) := x"03";
  constant CTRL_EN_ODD     : std_logic_vector(7 downto 0) := x"07";
  constant CTRL_LOOPBACK   : std_logic_vector(7 downto 0) := x"08";

  -- Patterns : data bit 0 at 1 and at 0, all parities
  type     data_array_t is array (natural range <>) of std_logic_vector(7 downto 0);
  constant PATTERNS        : data_array_t := (x"A5", x"5A", x"01", x"80", x"FF", x"00", x"3C", x"C3");

  -- Signals
  signal clk_i             : std_logic := '0';
  signal arst_b_i          : std_logic := '0';

  -- Interface SBI
  signal sbi_ini           : sbi_ini_t(addr (SBI_ADDR_WIDTH-1 downto 0), wdata(SBI_DATA_WIDTH-1 downto 0));
  signal sbi_tgt           : sbi_tgt_t(rdata(SBI_DATA_WIDTH-1 downto 0));

  -- UVVM SBI Interface
  signal sbi_if            : t_sbi_if(addr(SBI_ADDR_WIDTH-1 downto 0),
                                      wdata(SBI_DATA_WIDTH-1 downto 0),
                                      rdata(SBI_DATA_WIDTH-1 downto 0));

  -- Interface UART
  signal uart_tx           : std_logic;
  signal uart_rx           : std_logic := '1';
  signal uart_cts_b        : std_logic := '0';
  signal uart_rts_b        : std_logic;
  signal it_o              : std_logic;
  signal debug             : uart_debug_t;

  -- Expected parity bit
  function parity_bit(data   : std_logic_vector;
                      parity : parity_t) return std_logic is
    variable v : std_logic := '0';
  begin
    for i in data'range loop
      v := v xor data(i);
    end loop;
    if parity = PARITY_ODD then
      v := not v;
    end if;
    return v;
  end function;

  function to_string(parity : parity_t) return string is
  begin
    case parity is
      when PARITY_EVEN => return "even";
      when PARITY_ODD  => return "odd";
      when others      => return "none";
    end case;
  end function;

  -- CSR address on the SBI bus width
  function csr_addr(a : unsigned) return unsigned is
  begin
    return resize(a, SBI_ADDR_WIDTH);
  end function;

begin

  -- Clock and Reset Generation
  clk_i    <= not clk_i after CLK_PERIOD / 2;
  arst_b_i <= '0', '1' after 100 ns;

  -----------------------------------------------------------------------------
  -- DUT: SBI UART
  -----------------------------------------------------------------------------
  ins_dut : entity asylum.sbi_uart
    generic map (
      BAUD_RATE            => BAUD_RATE,
      CLOCK_FREQ           => CLOCK_FREQ,
      DEPTH_TX             => 16,
      DEPTH_RX             => 16
    )
    port map (
      clk_i                => clk_i,
      arst_b_i             => arst_b_i,
      sbi_ini_i            => sbi_ini,
      sbi_tgt_o            => sbi_tgt,
      uart_tx_o            => uart_tx,
      uart_rx_i            => uart_rx,
      uart_cts_b_i         => uart_cts_b,
      uart_rts_b_o         => uart_rts_b,
      it_o                 => it_o,
      debug_o              => debug
    );

  -- Mapping UVVM SBI IF to Asylum SBI Ports
  sbi_ini.cs    <= sbi_if.cs;
  sbi_ini.addr  <= std_logic_vector(sbi_if.addr(SBI_ADDR_WIDTH-1 downto 0));
  sbi_ini.re    <= sbi_if.rena;
  sbi_ini.we    <= sbi_if.wena;
  sbi_ini.wdata <= sbi_if.wdata(SBI_DATA_WIDTH-1 downto 0);
  sbi_if.ready  <= sbi_tgt.ready;
  sbi_if.rdata(SBI_DATA_WIDTH-1 downto 0) <= sbi_tgt.rdata;

  -----------------------------------------------------------------------------
  -- Stimulus
  -----------------------------------------------------------------------------
  process
    -- Simplified UART BFM procedure (Transmission to FPGA)
    -- corrupt_parity : send the inverted parity bit
    procedure uart_bfm_send(data           : std_logic_vector(7 downto 0);
                            period         : time;
                            parity         : parity_t := PARITY_NONE;
                            corrupt_parity : boolean  := false) is
    begin
      log(ID_SEQUENCER, "BFM UART: Sending 0x" & to_hstring(data) & " (parity " & to_string(parity) & ")", C_SCOPE);
      uart_rx <= '0'; -- Start bit
      wait for period;
      for i in 0 to 7 loop
        uart_rx <= data(i);
        wait for period;
      end loop;
      if parity /= PARITY_NONE then
        if corrupt_parity then
          uart_rx <= not parity_bit(data, parity);
        else
          uart_rx <=     parity_bit(data, parity);
        end if;
        wait for period;
      end if;
      uart_rx <= '1'; -- Stop bit
      wait for period;
    end procedure;

    -- UART monitor on uart_tx : receive one frame and check every bit
    procedure uart_bfm_expect(data   : std_logic_vector(7 downto 0);
                              parity : parity_t;
                              msg    : string) is
      variable v_data : std_logic_vector(7 downto 0);
    begin
      -- Wait start bit falling edge (it can be already started)
      if uart_tx /= '0' then
        wait until uart_tx = '0' for 4 * 12 * BIT_PERIOD;
        check_value(uart_tx, '0', ERROR, msg & " : start bit detected");
        wait for BIT_PERIOD/2;
      else
        wait for BIT_PERIOD/2 - uart_tx'last_event;
      end if;
      check_value(uart_tx, '0', ERROR, msg & " : start bit");
      for i in 0 to 7 loop
        wait for BIT_PERIOD;
        v_data(i) := uart_tx;
      end loop;
      check_value(v_data, data, ERROR, msg & " : data bits");
      if parity /= PARITY_NONE then
        wait for BIT_PERIOD;
        check_value(uart_tx, parity_bit(data, parity), ERROR, msg & " : parity bit (" & to_string(parity) & ")");
      end if;
      wait for BIT_PERIOD;
      check_value(uart_tx, '1', ERROR, msg & " : stop bit");
      -- Stay in the stop bit
      wait for BIT_PERIOD/4;
    end procedure;

    -- RX test : BFM send, read data by SBI, check parity error flag
    procedure test_rx(data           : std_logic_vector(7 downto 0);
                      parity         : parity_t;
                      corrupt_parity : boolean := false) is
      variable v_err : std_logic;
    begin
      uart_bfm_send(data, BIT_PERIOD, parity, corrupt_parity);
      wait until rising_edge(clk_i);
      if corrupt_parity then v_err := '1'; else v_err := '0'; end if;
      check_value(debug.uart_rx.parity_error, v_err, ERROR, "Check RX parity error flag for 0x" & to_hstring(data));
      sbi_check(csr_addr(UART_DATA), data, "Check UART RX 0x" & to_hstring(data) & " (parity " & to_string(parity) & ")", clk_i, sbi_if);
    end procedure;

    -- TX test : write data by SBI, check the frame on uart_tx
    procedure test_tx(data   : std_logic_vector(7 downto 0);
                      parity : parity_t) is
    begin
      sbi_write(csr_addr(UART_DATA), data, "Write UART TX 0x" & to_hstring(data), clk_i, sbi_if);
      uart_bfm_expect(data, parity, "Check UART TX 0x" & to_hstring(data) & " (parity " & to_string(parity) & ")");
    end procedure;

    -- Loopback test : write data by SBI, check frame on uart_tx and read it back
    procedure test_loopback(data       : std_logic_vector(7 downto 0);
                            parity     : parity_t;
                            exp_error  : std_logic := '0') is
    begin
      test_tx(data, parity);
      wait for BIT_PERIOD;
      check_value(debug.uart_rx.parity_error, exp_error, ERROR, "Check loopback RX parity error flag for 0x" & to_hstring(data));
      sbi_check(csr_addr(UART_DATA), data, "Check loopback RX 0x" & to_hstring(data), clk_i, sbi_if);
    end procedure;

    variable v_parity : parity_t;
    variable v_ctrl   : std_logic_vector(7 downto 0);
  begin
    -- Initialisation
    sbi_if <= init_sbi_if_signals(SBI_ADDR_WIDTH, SBI_DATA_WIDTH);
    wait until arst_b_i = '1';
    wait until rising_edge(clk_i);
    log(ID_SEQUENCER, "Reset released, starting simulation", C_SCOPE);

    sbi_write(csr_addr(UART_CTRL_RX), CTRL_EN, "Enable UART RX", clk_i, sbi_if);

    -- TEST 1: Nominal Reception
    log(ID_LOG_HDR, "Test 1: Nominal Case (115200)", C_SCOPE);
    uart_bfm_send(x"A5", BIT_PERIOD);

    -- Wait for data to be available (polling status if available, or simple wait)
    wait for 15 * BIT_PERIOD;

    sbi_check(csr_addr(UART_DATA), x"A5", "Check UART RX Nominal", clk_i, sbi_if);

    -- TEST 2: Clock Drift Stress Test (Risk of connection loss)
    log(ID_LOG_HDR, "Test 2: Clock Drift +3% (Stress Test)", C_SCOPE);
    uart_bfm_send(x"55", BIT_PERIOD * 1.03);

    wait for 15 * BIT_PERIOD;

    sbi_check(csr_addr(UART_DATA), x"55", "Check UART RX Drift +3%", clk_i, sbi_if);

    -- TEST 3: Clock Drift Stress Test (Negative drift)
    log(ID_LOG_HDR, "Test 3: Clock Drift -3% (Stress Test)", C_SCOPE);
    uart_bfm_send(x"3C", BIT_PERIOD * 0.97);

    wait for 15 * BIT_PERIOD;

    sbi_check(csr_addr(UART_DATA), x"3C", "Check UART RX Drift -3%", clk_i, sbi_if);

    -- TEST 4: Fake Start Bit (Glitch)
    log(ID_LOG_HDR, "Test 4: Fake Start Bit (Glitch)", C_SCOPE);
    uart_rx <= '0';
    wait for BIT_PERIOD / 4; -- Glitch shorter than half bit period
    uart_rx <= '1';
    wait for 10 * BIT_PERIOD;
    -- isr[2] is the "RX FIFO not empty" interrupt, captured only when unmasked
    sbi_write(csr_addr(UART_IMR), x"04", "Unmask RX not empty interrupt", clk_i, sbi_if);
    wait until rising_edge(clk_i);
    sbi_check(csr_addr(UART_ISR), x"00", "Check RX FIFO is still empty", clk_i, sbi_if);
    check_value(it_o, '0', ERROR, "Check no interrupt after glitch");
    uart_bfm_send(x"C6", BIT_PERIOD);
    wait until rising_edge(clk_i);
    wait until rising_edge(clk_i);
    sbi_check(csr_addr(UART_ISR), x"04", "Check RX not empty interrupt", clk_i, sbi_if);
    check_value(it_o, '1', ERROR, "Check interrupt output after reception");
    sbi_check(csr_addr(UART_DATA), x"C6", "Check UART RX after glitch", clk_i, sbi_if);
    sbi_write(csr_addr(UART_IMR), x"00", "Mask RX not empty interrupt", clk_i, sbi_if);
    sbi_write(csr_addr(UART_ISR), x"04", "Clear RX not empty interrupt", clk_i, sbi_if);
    sbi_check(csr_addr(UART_ISR), x"00", "Check interrupt cleared", clk_i, sbi_if);
    check_value(it_o, '0', ERROR, "Check interrupt output cleared");

    -- TEST 5: RX with parity (even / odd), good and corrupted parity
    for p in 0 to 1 loop
      if p = 0 then
        v_parity := PARITY_EVEN; v_ctrl := CTRL_EN_EVEN;
      else
        v_parity := PARITY_ODD;  v_ctrl := CTRL_EN_ODD;
      end if;
      log(ID_LOG_HDR, "Test 5." & integer'image(p) & ": RX with " & to_string(v_parity) & " parity", C_SCOPE);
      sbi_write(csr_addr(UART_CTRL_RX), v_ctrl, "Enable UART RX with " & to_string(v_parity) & " parity", clk_i, sbi_if);
      sbi_check(csr_addr(UART_CTRL_RX), v_ctrl, "Read back ctrl_rx", clk_i, sbi_if);
      for i in PATTERNS'range loop
        test_rx(PATTERNS(i), v_parity);
      end loop;
      log(ID_SEQUENCER, "RX with corrupted " & to_string(v_parity) & " parity", C_SCOPE);
      test_rx(x"A5", v_parity, corrupt_parity => true);
      test_rx(x"5A", v_parity, corrupt_parity => false);
      test_rx(x"01", v_parity, corrupt_parity => true);
    end loop;

    -- Back to no parity : parity error flag is cleared
    log(ID_LOG_HDR, "Test 5.2: RX without parity after parity tests", C_SCOPE);
    sbi_write(csr_addr(UART_CTRL_RX), CTRL_EN, "Enable UART RX without parity", clk_i, sbi_if);
    test_rx(x"81", PARITY_NONE);
    test_rx(x"7E", PARITY_NONE);

    -- TEST 6: TX with and without parity
    for p in 0 to 2 loop
      if p = 0 then
        v_parity := PARITY_NONE; v_ctrl := CTRL_EN;
      elsif p = 1 then
        v_parity := PARITY_EVEN; v_ctrl := CTRL_EN_EVEN;
      else
        v_parity := PARITY_ODD;  v_ctrl := CTRL_EN_ODD;
      end if;
      log(ID_LOG_HDR, "Test 6." & integer'image(p) & ": TX with parity " & to_string(v_parity), C_SCOPE);
      sbi_write(csr_addr(UART_CTRL_TX), v_ctrl, "Enable UART TX with parity " & to_string(v_parity), clk_i, sbi_if);
      sbi_check(csr_addr(UART_CTRL_TX), v_ctrl, "Read back ctrl_tx", clk_i, sbi_if);
      for i in PATTERNS'range loop
        test_tx(PATTERNS(i), v_parity);
      end loop;
      -- Back to back frames (FIFO TX)
      log(ID_SEQUENCER, "TX back to back frames with parity " & to_string(v_parity), C_SCOPE);
      sbi_write(csr_addr(UART_DATA), x"96", "Write UART TX 0x96", clk_i, sbi_if);
      sbi_write(csr_addr(UART_DATA), x"69", "Write UART TX 0x69", clk_i, sbi_if);
      uart_bfm_expect(x"96", v_parity, "Check UART TX back to back 0x96");
      uart_bfm_expect(x"69", v_parity, "Check UART TX back to back 0x69");
      sbi_write(csr_addr(UART_CTRL_TX), x"00", "Disable UART TX", clk_i, sbi_if);
    end loop;

    -- TEST 7: Internal loopback (uart_rx <= uart_tx) with parity
    for p in 0 to 2 loop
      if p = 0 then
        v_parity := PARITY_NONE; v_ctrl := CTRL_EN;
      elsif p = 1 then
        v_parity := PARITY_EVEN; v_ctrl := CTRL_EN_EVEN;
      else
        v_parity := PARITY_ODD;  v_ctrl := CTRL_EN_ODD;
      end if;
      log(ID_LOG_HDR, "Test 7." & integer'image(p) & ": Loopback with parity " & to_string(v_parity), C_SCOPE);
      sbi_write(csr_addr(UART_CTRL_TX), v_ctrl                  , "Enable UART TX", clk_i, sbi_if);
      sbi_write(csr_addr(UART_CTRL_RX), v_ctrl or CTRL_LOOPBACK , "Enable UART RX in loopback", clk_i, sbi_if);
      for i in PATTERNS'range loop
        test_loopback(PATTERNS(i), v_parity);
      end loop;
    end loop;

    -- TEST 8: Loopback with parity mismatch (TX even, RX odd) => parity error
    log(ID_LOG_HDR, "Test 8: Loopback with parity mismatch (TX even, RX odd)", C_SCOPE);
    sbi_write(csr_addr(UART_CTRL_TX), CTRL_EN_EVEN                , "Enable UART TX even parity", clk_i, sbi_if);
    sbi_write(csr_addr(UART_CTRL_RX), CTRL_EN_ODD or CTRL_LOOPBACK, "Enable UART RX odd parity in loopback", clk_i, sbi_if);
    test_loopback(x"A5", PARITY_EVEN, exp_error => '1');
    test_loopback(x"01", PARITY_EVEN, exp_error => '1');
    sbi_write(csr_addr(UART_CTRL_RX), CTRL_EN_EVEN or CTRL_LOOPBACK, "Enable UART RX even parity in loopback", clk_i, sbi_if);
    test_loopback(x"01", PARITY_EVEN, exp_error => '0');

    sbi_write(csr_addr(UART_IMR), x"04", "Unmask RX not empty interrupt", clk_i, sbi_if);
    wait until rising_edge(clk_i);
    sbi_check(csr_addr(UART_ISR), x"00", "Check RX FIFO is empty at end of test", clk_i, sbi_if);
    check_value(it_o, '0', ERROR, "Check no pending interrupt at end of test");

    log(ID_LOG_HDR, "Simulation Finished.", C_SCOPE);
    report_alert_counters(FINAL);
    log(ID_LOG_HDR, "SIMULATION COMPLETED", C_SCOPE);

    -- Finish the simulation
    std.env.stop;
    wait;
  end process;

end sim;
